---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: elastic
provisioner: aws.io/aws-efs

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-storage-claim
  namespace: carbo-test
  annotations:  
    volume.beta.kubernetes.io/storage-class: elastic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-lifecycle-claim
  namespace: carbo-test
  annotations:  
    volume.beta.kubernetes.io/storage-class: elastic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

